### ISSUE TITLE
panic: standard_init_linux.go:178: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by 4n3w** [galexrt/elasticsearch-operator#2]
**What did you do?**

Tried to create the operator with ```kubectl create -f bundle.yaml```

**What did you expect to see?**

I expected to see the TPRs when I run ```kubectl get thirdpartyresources``` but I get:

```> kubectl get thirdpartyresource
NAME                                    DESCRIPTION                           VERSION(S)
alertmanager.monitoring.coreos.com      Managed Alertmanager cluster          v1alpha1
prometheus.monitoring.coreos.com        Managed Prometheus server             v1alpha1
service-monitor.monitoring.coreos.com   Prometheus monitoring for a service   v1alpha1
```
(From prior installs of the prometheus operator)

**What did you see instead? Under which circumstances?**

    > kubectl create -f bundle.yaml
    serviceaccount "elasticsearch-operator" created
    deployment "elasticsearch-operator" created
    Error from server (BadRequest): error when creating "bundle.yaml": ClusterRoleBinding in version 
    "v1beta1" cannot be handled as a ClusterRoleBinding: no kind "ClusterRoleBinding" is registered 
    for version "rbac.authorization.k8s.io/v1beta1"
    Error from server (BadRequest): error when creating "bundle.yaml": ClusterRole in version 
    "v1beta1" cannot be handled as a ClusterRole: no kind "ClusterRole" is registered for version 
    "rbac.authorization.k8s.io/v1beta1"

Then in kubectl I see the operator pod has been created but it's CrashLooping:

    elasticsearch-operator-4088573788-cfv24            0/1       CrashLoopBackOff   5          4m

**Environment**

CoreOS/Kubernetes 1.5.5

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5", GitCommit:"894ff23729bbc0055907dd3a496afb725396adda", GitTreeState:"clean", BuildDate:"2017-03-23T16:14:24Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5+coreos.0", GitCommit:"e2cd7718ba844e874a68aa13f8f5bb0728b415bb", GitTreeState:"clean", BuildDate:"2017-03-22T01:59:35Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Manually installed coreos on-prem 13 node, managed with ansible. 

* Prometheus Operator Logs:

```
> kubectl logs elasticsearch-operator-4088573788-cfv24
panic: standard_init_linux.go:178: exec user process caused "no such file or directory" [recovered]
	panic: standard_init_linux.go:178: exec user process caused "no such file or directory"

goroutine 1 [running, locked to thread]:
panic(0x7eb2e0, 0xc82013acb0)
	/usr/lib/go1.6/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8200a32f8)
	/build/amd64-usr/var/tmp/portage/app-emulation/runc-1.0.0_rc2_p9/work/runc-1.0.0_rc2_p9/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7eb2e0, 0xc82013acb0)
	/usr/lib/go1.6/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc8200a2c08, 0xc8200220a8, 0xc8200a2d18)
	/build/amd64-usr/var/tmp/portage/app-emulation/runc-1.0.0_rc2_p9/work/runc-1.0.0_rc2_p9/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc8200608c0, 0x7f542cd374d0, 0xc82013acb0)
	/build/amd64-usr/var/tmp/portage/app-emulation/runc-1.0.0_rc2_p9/work/runc-1.0.0_rc2_p9/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc820080780, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/runc-1.0.0_rc2_p9/work/runc-1.0.0_rc2_p9/main_unix.go:26 +0x68
reflect.Value.call(0x74fac0, 0x9012a0, 0x13, 0x847808, 0x4, 0xc8200a3278, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/lib/go1.6/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74fac0, 0x9012a0, 0x13, 0xc8200a3278, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go1.6/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x74fac0, 0x9012a0, 0xc820080780, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/runc-1.0.0_rc2_p9/work/runc-1.0.0_rc2_p9/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x84a6b8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8e05e0, 0x51, 0x0, ...)
	/build/amd64-usr/var/tmp/portage/app-emulation/runc-1.0.0_rc2_p9/work/runc-1.0.0_rc2_p9/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001980, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/runc-1.0.0_rc2_p9/work/runc-1.0.0_rc2_p9/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/build/amd64-usr/var/tmp/portage/app-emulation/runc-1.0.0_rc2_p9/work/runc-1.0.0_rc2_p9/main.go:137 +0xe24

```

**Comment by galexrt** [comment]
I'm currently working on this issue. Sorry about the issue.

**Comment by galexrt** [comment]
@4n3w Could you please try re-pulling the image and see if the issue is now gone?
There seemed to be an issue with the build instructions that should now have been fixed.

**Comment by galexrt** [comment]
Closing as no response from issue creator and additionally not reproducible as written in the above comment.
